### ISSUE TITLE
Bug avec le mod aether

### ISSUE THREAD

**Issue by dowichat** [Cazzar/JukeboxReloaded#11]
J'ai un bug de crash avec la version de Jukebox-Reloaded-1.7.10-3.0.0-universal et j'utilise le core CazzarCoreLib-1.2.0-SNAPSHOT-universal.jar. Je joue en multijoueur avec ce mod depuis un moment sans problème. Mais depuis que j'ai installé le mod aether-1.7.10-v1.1.0.jar quand je vient pour lire de la musique dans le jukebox le jeu crash avec l'erreur:  java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1443)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:270)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2013)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Cazzar** [comment]
This mod has not been updated for 6 years, and I am no longer modding Minecraft, if someone else would like to pick this project up, they can, though I am going to close this off as it will not be fixed.
